### ISSUE TITLE
idea/help: cflag testing

### ISSUE THREAD

**Issue by telans** [toralf/tinderbox#2]
I've managed to get the tinderbox up and running for the guru overlay which is great. Some hiccups, but it works really well. I'd like to try set it up to automate testing of cflags, in particular -flto and other default optimisations of gentooLTO.

Setting up gentooLTO in setup_img.sh seems easy enough, however, I'm not sure where to start in clearing modified cflags (with something like package.env) if an emerge fails during src_compile. Ideally I would have a package re-emerged with default cflags to see if it suceeds, and if it does an email would fire off stating so.

As most of job.sh goes over my head, could you give some pointers as to which functions I should look at implementing this in? Thanks.

**Comment by toralf** [comment]
> I've managed to get the tinderbox up and running for the guru overlay which is great. Some hiccups, but it works really well.

Great

> , in particular -flto and other default optimisations of gentooLTO.

IMO you've to expect much longer compile times, right?

> could you give some pointers 

Sure, that's one of the key feature of the tinderbox. It ensures, that a failed package (due to special flags) does not incredible lowers down the coverage of the tree due to be a dep for almost all others.

Please look for _try_again_ . If true (==1) then the failed package is added to a  _/etc/portage/package.env/*_ file which corresponds to the appropriate _/etc/portage/env/*_ file containing the safe default flags.

Around line 888 in _GotAnIssue()_ the failed package atom is then added to _backlog.1st_ so it will become the first package in _getNextTask()_ due to the precedence order of _setTaskAndBacklog()_

> As most of job.sh goes over my head, 

I missed the point of _no return_ when I started with a simple bash 1-liner and just added few KLOC. Sry ;)

**Comment by toralf** [comment]
BTW I do use this cronjob to save CPU cycles at n-1 images, if at 1 image a package failed due to CFLAGS settings (assuming, that CFLAGS was the culprit):
```
# save cpu cycles
@hourly  f=/tmp/cflagsknown2fail; sort -u ~/run/*/etc/portage/package.env/cflags_default 2>/dev/null | column -t >$f && for i in $(ls -d ~/run/*/etc/portage/package.env/ 2>/dev/null); do cp $f $i; done
```

**Comment by telans** [comment]
Thanks for the tip. I've been ill, haven't been able to get round to it until now. Hopefully I don't find out I've messed up setting up gentoolto 5 hours into installation...
